{
  "version": 2.0,
  "success": true,
  "reason": null,
  "content": {
    "org_id": 202,
    "min_id": 2176,
    "max_id": 2176,
    "playbook_content": {
      "2176": [
        {
          "id": 384,
          "playbook": {
            "id": 186,
            "display_name": "PB: Export Playbook",
            "activation_type": "manual",
            "description": null,
            "creator_principal": {
              "id": 8,
              "type": "user",
              "name": "a@example.com",
              "display_name": "Resilient Sysadmin"
            },
            "is_deleted": false,
            "type": "default",
            "version": 16
          },
          "start_time": 1670525188560,
          "last_activity_time": 1670525192173,
          "last_activity_by": {
            "id": 8,
            "type": "user",
            "name": "a@example.com",
            "display_name": "Resilient Sysadmin"
          },
          "elapsed_time": 3613,
          "status": "error",
          "object": {
            "parent": null,
            "object_id": 2176,
            "object_name": "test odbc",
            "type_id": 0,
            "type_name": "incident"
          },
          "object_is_deleted": false,
          "incident_id": 2176,
          "detail_msg": "The playbook was terminated by the system due to a function error. This error occurs in playbook 'PB: Export Playbook'.\nERROR:\n\npost() got an unexpected keyword argument 'headers'\n  File \"/Users/markscherfling/.pyenv/versions/3.9.13/lib/python3.9/site-packages/circuits/core/manager.py\", line 874, in processTask\n    raise value.extract()\n  File \"/Users/markscherfling/.pyenv/versions/3.9.13/lib/python3.9/site-packages/resilient_circuits/actions_component.py\", line 90, in _on_task\n    yield result.get()\n  File \"/Users/markscherfling/.pyenv/versions/3.9.13/lib/python3.9/multiprocessing/pool.py\", line 771, in get\n    raise self._value\n  File \"/Users/markscherfling/.pyenv/versions/3.9.13/lib/python3.9/multiprocessing/pool.py\", line 125, in worker\n    result = (True, func(*args, **kwds))\n  File \"/Users/markscherfling/.pyenv/versions/3.9.13/lib/python3.9/site-packages/resilient_circuits/decorators.py\", line 274, in _invoke_app_function\n    for r in fn_results:\n  File \"/Users/markscherfling/repos/resilient-community-apps/fn_playbook_utils/fn_playbook_utils/components/funct_pb_export_playbook.py\", line 34, in _app_function\n    status, results = export_playbook(self.rest_client(),\n  File \"/Users/markscherfling/repos/resilient-community-apps/fn_playbook_utils/fn_playbook_utils/lib/common.py\", line 235, in export_playbook\n    export_result = rest_client.post(posixpath.join(PLAYBOOK_URL, \"exports\", str(export_start_result.get(\"export_id\"))),\n\nStarting App Function: 'pb_export_playbook'"
        },
        {
          "id": 385,
          "playbook": {
            "id": 186,
            "display_name": "PB: Export Playbook",
            "activation_type": "manual",
            "description": null,
            "creator_principal": {
              "id": 8,
              "type": "user",
              "name": "a@example.com",
              "display_name": "Resilient Sysadmin"
            },
            "is_deleted": false,
            "type": "default",
            "version": 16
          },
          "start_time": 1670525259234,
          "last_activity_time": 1670525319335,
          "last_activity_by": {
            "id": 8,
            "type": "user",
            "name": "a@example.com",
            "display_name": "Resilient Sysadmin"
          },
          "elapsed_time": 60101,
          "status": "completed",
          "object": {
            "parent": null,
            "object_id": 2176,
            "object_name": "test odbc",
            "type_id": 0,
            "type_name": "incident"
          },
          "object_is_deleted": false,
          "incident_id": 2176,
          "detail_msg": null
        },
        {
          "id": 386,
          "playbook": {
            "id": 185,
            "display_name": "PB: Get Playbooks",
            "activation_type": "manual",
            "description": "Returns playbooks based on filter criteria",
            "creator_principal": {
              "id": 8,
              "type": "user",
              "name": "a@example.com",
              "display_name": "Resilient Sysadmin"
            },
            "is_deleted": false,
            "type": "default",
            "version": 11
          },
          "start_time": 1670525335803,
          "last_activity_time": 1670525338816,
          "last_activity_by": {
            "id": 8,
            "type": "user",
            "name": "a@example.com",
            "display_name": "Resilient Sysadmin"
          },
          "elapsed_time": 3013,
          "status": "completed",
          "object": {
            "parent": null,
            "object_id": 2176,
            "object_name": "test odbc",
            "type_id": 0,
            "type_name": "incident"
          },
          "object_is_deleted": false,
          "incident_id": 2176,
          "detail_msg": null
        },
        {
          "id": 387,
          "playbook": {
            "id": 187,
            "display_name": "PB: Import Playbook",
            "activation_type": "manual",
            "description": null,
            "creator_principal": {
              "id": 8,
              "type": "user",
              "name": "a@example.com",
              "display_name": "Resilient Sysadmin"
            },
            "is_deleted": false,
            "type": "default",
            "version": 19
          },
          "start_time": 1670525580214,
          "last_activity_time": 1670525675841,
          "last_activity_by": {
            "id": 8,
            "type": "user",
            "name": "a@example.com",
            "display_name": "Resilient Sysadmin"
          },
          "elapsed_time": 95627,
          "status": "error",
          "object": {
            "parent": null,
            "object_id": 2176,
            "object_name": "test odbc",
            "type_id": 0,
            "type_name": "incident"
          },
          "object_is_deleted": false,
          "incident_id": 2176,
          "detail_msg": "The playbook was terminated by the system due to a function error. This error occurs in playbook 'PB: Import Playbook'.\nERROR:\n\nConnectionError(ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')))\n  File \"/Users/markscherfling/.pyenv/versions/3.9.13/lib/python3.9/site-packages/circuits/core/manager.py\", line 874, in processTask\n    raise value.extract()\n  File \"/Users/markscherfling/.pyenv/versions/3.9.13/lib/python3.9/site-packages/resilient_circuits/actions_component.py\", line 90, in _on_task\n    yield result.get()\n  File \"/Users/markscherfling/.pyenv/versions/3.9.13/lib/python3.9/multiprocessing/pool.py\", line 771, in get\n    raise self._value\n  File \"/Users/markscherfling/.pyenv/versions/3.9.13/lib/python3.9/multiprocessing/pool.py\", line 125, in worker\n    result = (True, func(*args, **kwds))\n  File \"/Users/markscherfling/.pyenv/versions/3.9.13/lib/python3.9/site-packages/resilient_circuits/decorators.py\", line 274, in _invoke_app_function\n    for r in fn_results:\n  File \"/Users/markscherfling/repos/resilient-community-apps/fn_playbook_utils/fn_playbook_utils/components/funct_pb_import_playbook.py\", line 36, in _app_function\n    results = import_playbook(self.rest_client(), content)\n  File \"/Users/markscherfling/repos/resilient-community-apps/fn_playbook_utils/fn_playbook_utils/lib/common.py\", line 255, in import_playbook\n    raise IntegrationError(upload_exception)\n\nStarting App Function: 'pb_import_playbook'"
        },
        {
          "id": 388,
          "playbook": {
            "id": 187,
            "display_name": "PB: Import Playbook",
            "activation_type": "manual",
            "description": null,
            "creator_principal": {
              "id": 8,
              "type": "user",
              "name": "a@example.com",
              "display_name": "Resilient Sysadmin"
            },
            "is_deleted": false,
            "type": "default",
            "version": 19
          },
          "start_time": 1670527178150,
          "last_activity_time": 1670527720870,
          "last_activity_by": {
            "id": 8,
            "type": "user",
            "name": "a@example.com",
            "display_name": "Resilient Sysadmin"
          },
          "elapsed_time": 542720,
          "status": "error",
          "object": {
            "parent": null,
            "object_id": 2176,
            "object_name": "test odbc",
            "type_id": 0,
            "type_name": "incident"
          },
          "object_is_deleted": false,
          "incident_id": 2176,
          "detail_msg": "The playbook was terminated by the system due to a function error. This error occurs in playbook 'PB: Import Playbook'.\nERROR:\n\nConnectionError(ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')))\n  File \"/Users/markscherfling/.pyenv/versions/3.9.13/lib/python3.9/site-packages/circuits/core/manager.py\", line 874, in processTask\n    raise value.extract()\n  File \"/Users/markscherfling/.pyenv/versions/3.9.13/lib/python3.9/site-packages/resilient_circuits/actions_component.py\", line 90, in _on_task\n    yield result.get()\n  File \"/Users/markscherfling/.pyenv/versions/3.9.13/lib/python3.9/multiprocessing/pool.py\", line 771, in get\n    raise self._value\n  File \"/Users/markscherfling/.pyenv/versions/3.9.13/lib/python3.9/multiprocessing/pool.py\", line 125, in worker\n    result = (True, func(*args, **kwds))\n  File \"/Users/markscherfling/.pyenv/versions/3.9.13/lib/python3.9/site-packages/resilient_circuits/decorators.py\", line 274, in _invoke_app_function\n    for r in fn_results:\n  File \"/Users/markscherfling/repos/resilient-community-apps/fn_playbook_utils/fn_playbook_utils/components/funct_pb_import_playbook.py\", line 36, in _app_function\n    results = import_playbook(self.rest_client(), content)\n  File \"/Users/markscherfling/repos/resilient-community-apps/fn_playbook_utils/fn_playbook_utils/lib/common.py\", line 255, in import_playbook\n    raise IntegrationError(upload_exception)\n\nStarting App Function: 'pb_import_playbook'\nStarting App Function: 'pb_import_playbook'"
        },
        {
          "id": 389,
          "playbook": {
            "id": 187,
            "display_name": "PB: Import Playbook",
            "activation_type": "manual",
            "description": null,
            "creator_principal": {
              "id": 8,
              "type": "user",
              "name": "a@example.com",
              "display_name": "Resilient Sysadmin"
            },
            "is_deleted": false,
            "type": "default",
            "version": 20
          },
          "start_time": 1670530126645,
          "last_activity_time": 1670530222531,
          "last_activity_by": {
            "id": 8,
            "type": "user",
            "name": "a@example.com",
            "display_name": "Resilient Sysadmin"
          },
          "elapsed_time": 95886,
          "status": "error",
          "object": {
            "parent": null,
            "object_id": 2176,
            "object_name": "test odbc",
            "type_id": 0,
            "type_name": "incident"
          },
          "object_is_deleted": false,
          "incident_id": 2176,
          "detail_msg": "The playbook was terminated by the system due to a function error. This error occurs in playbook 'PB: Import Playbook'.\nERROR:\n\nConnectionError(ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')))\n  File \"/Users/markscherfling/.pyenv/versions/3.9.13/lib/python3.9/site-packages/circuits/core/manager.py\", line 874, in processTask\n    raise value.extract()\n  File \"/Users/markscherfling/.pyenv/versions/3.9.13/lib/python3.9/site-packages/resilient_circuits/actions_component.py\", line 90, in _on_task\n    yield result.get()\n  File \"/Users/markscherfling/.pyenv/versions/3.9.13/lib/python3.9/multiprocessing/pool.py\", line 771, in get\n    raise self._value\n  File \"/Users/markscherfling/.pyenv/versions/3.9.13/lib/python3.9/multiprocessing/pool.py\", line 125, in worker\n    result = (True, func(*args, **kwds))\n  File \"/Users/markscherfling/.pyenv/versions/3.9.13/lib/python3.9/site-packages/resilient_circuits/decorators.py\", line 274, in _invoke_app_function\n    for r in fn_results:\n  File \"/Users/markscherfling/repos/resilient-community-apps/fn_playbook_utils/fn_playbook_utils/components/funct_pb_import_playbook.py\", line 36, in _app_function\n    results = import_playbook(self.rest_client(), content)\n  File \"/Users/markscherfling/repos/resilient-community-apps/fn_playbook_utils/fn_playbook_utils/lib/common.py\", line 255, in import_playbook\n    raise IntegrationError(upload_exception)\n\nStarting App Function: 'pb_import_playbook'"
        },
        {
          "id": 390,
          "playbook": {
            "id": 187,
            "display_name": "PB: Import Playbook",
            "activation_type": "manual",
            "description": null,
            "creator_principal": {
              "id": 8,
              "type": "user",
              "name": "a@example.com",
              "display_name": "Resilient Sysadmin"
            },
            "is_deleted": false,
            "type": "default",
            "version": 21
          },
          "start_time": 1670531751910,
          "last_activity_time": 1670531759942,
          "last_activity_by": {
            "id": 8,
            "type": "user",
            "name": "a@example.com",
            "display_name": "Resilient Sysadmin"
          },
          "elapsed_time": 8032,
          "status": "completed",
          "object": {
            "parent": null,
            "object_id": 2176,
            "object_name": "test odbc",
            "type_id": 0,
            "type_name": "incident"
          },
          "object_is_deleted": false,
          "incident_id": 2176,
          "detail_msg": null
        }
      ]
    }
  },
  "raw": null,
  "inputs": {
    "pb_max_incident_id": 2176,
    "pb_min_incident_date": null,
    "pb_max_incident_date": null,
    "pb_min_incident_id": 2176
  },
  "metrics": {
    "version": "1.0",
    "package": "fn-playbook-utils",
    "package_version": "1.1.0",
    "host": "localhost",
    "execution_time_ms": 623,
    "timestamp": "2022-12-08 15:41:06"
  }
}